export const A_GET_USERS = 'A_GET_USERS'
export const A_EDIT_USER = 'A_EDIT_USER'
export const A_DELETE_USER = 'A_DELETE_USER'
export const A_ADD_USER = 'A_ADD_USER'
export const A_SET_USERS_PER_PAGE = 'A_SET_USERS_PER_PAGE'
